name = "school-sos-backend"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "school-sos-db"
database_id = "ebedc93d-0faa-427d-902e-d532f48c2fcc"
migrations_dir = "migrations"
